version: '3'
services:
  app:
    command: tail -f /dev/null
    build: .
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./local_files:/app/local_files
      - ./local_files/output:/app/local_files/output
      - ./data:/data
